name: podcast
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^1.5.0
  intl: ^0.15.8
  webfeed: ^0.4.2
  http: ^0.12.0+2
  provider: ^3.1.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg

